project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "malbertzard"
  navbar:
    left:
      - content/posts.qmd
    right:
      - content/about.qmd
      - icon: github
        href: https://github.com/malbertzard

format:
  html:
    theme: litera
    css: styles.css



